Refactor deploy workflow to improve readability.
Group related steps under clear names and combine commands for efficiency. This enhances the workflow's clarity and maintainability without altering its functionality.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,25 +27,32 @@ jobs:
         with:
           submodules: recursive
           fetch-depth: 0
+
       - name: Setup Pages
         id: pages
         uses: actions/configure-pages@v3
+
       - uses: actions/setup-python@v4
         with:
           python-version: 3.x
-      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
+
+      - name: Cache ID
+        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
+
       - uses: actions/cache@v3
         with:
           key: mkdocs-material-${{ env.cache_id }}
           path: .cache
           restore-keys: |
             mkdocs-material-
-      - run: pip install mkdocs-material --no-cache-dir
-      - run: mkdocs build
-      - name: Verify site directory
-        run: test -d site && echo "Site directory exists" || echo "Missing site directory"
-      - name: Verify site build output
-        run: ls -la site
+
+      - name: Build website
+        run: |
+          pip install mkdocs-material --no-cache-dir
+          mkdocs build
+          test -d site && echo "Site directory exists" || echo "Missing site directory"
+          ls -la site
+
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
